### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by oganm** [tanaydin/tckimlik2personalInformation#1]
Not publishing a license in github defaults to a slightly modified version of "all rights reserved" type of license. Which prevents anyone else from modifying it which I assume is not something you intended to do. Also since your code uses a snippet that was published under GPL 2, you are obligated to publish it with a GPL 2 or a less restrictive license

**Comment by canerbasaran** [comment]
GPLv2, GPLv3 or AGPLv3

**Comment by tanaydin** [comment]
Close 42a63bb612829186df92e8752704b96f20a10be9
