### ISSUE TITLE
öneri

### ISSUE THREAD

**Issue by daft117** [tanaydin/tckimlik2personalInformation#3]
for range yerine while daha şukela olur.
nitekim 32 bit python 2.7 de range büyük geliyor
ayrıca site cortlamış/kodları değiştirmiş olabilir

**Comment by tanaydin** [comment]
bu kodu probleme örnek olması açısından yazdım. kodu optimize etmek mümkündür tabiki. range'in patlaması iyi, kafası çalışsın biraz çalıştırmaya çalışanın :)

site değişti, artık vermiyorlar bu bilgileri.
